### ISSUE TITLE
Covert from json to yaml where json key is empty string and vice verse

### ISSUE THREAD

**Issue by zd-dalibor** [jeremyfa/yaml.js#10]
Covert from json to yaml where json key is empty string and vice verse.

e.g.

``` json
{
    "": "test"
}
```

When I try to convert to yaml I get this result:

``` yaml
 : test
```

When I try to convert converted yaml back to json I get this:

``` json
{
   "test"
}
```

**Comment by jeremyfa** [comment]
Will take a look. Thanks for the feedback!

**Comment by jeremyfa** [comment]
This has been fixed in `v0.2.0`
