### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by ravitej177** [jeremyfa/yaml.js#102]
on webpacker compilation it is returning " Module not found: Error: Can't resolve 'fs' "

**Comment by ravitej177** [comment]
Module not found: Error: Can't resolve 'fs' in /node_modules/yamljs/lib'
 @ ./node_modules/yamljs/lib/Utils.js 274:11-20
 @ ./node_modules/yamljs/lib/Yaml.js

**Comment by jeremyfa** [comment]
#104

**Comment by SimonaMitrenova** [comment]
add this to your config:

node: {
fs: "empty"
}

**Comment by Remo** [comment]
thanks @SimonaMitrenova 

here's what I had to do with laravel-mix:

```javascript
mix.webpackConfig({
  node: {
    fs: 'empty'
  }
});
```

**Comment by Artistan** [comment]
Thanks @Remo , looking for that fix for awhile now.

**Comment by soumendutmec** [comment]
> add this to your config:
> 
> node: {
> fs: "empty"
> }

which config didn't get

**Comment by ahsanplusplus** [comment]
Can you let me know where should I add it on Angular 10?

**Comment by prmichaelsen** [comment]
this isn't a real solution

**Comment by keisanng** [comment]
Svelte config:

```js
module.exports = {
  compilerOptions: {
    namespace: "foreign"
  },
  preprocess: [ sveltePreprocess(), svelteNativePreprocessor() ],
  webpackConfig: {
    node: {
      fs: "empty"
    }
  }
```
