### ISSUE TITLE
incorrect boolean conversion from json to yaml.

### ISSUE THREAD

**Issue by JamesKyburz** [jeremyfa/yaml.js#108]
```
ᐅ echo "{\"hello\": \"yes\"}" | json2yaml -
hello: yes
```

The yaml needs to quote boolean keywords when the json contains them as strings.

**Comment by jeremyfa** [comment]
`yes` is not a boolean keyword anymore in Yaml 1.2 spec so `yes` is perfectly valid and equivalent to `'yes'` and thus doesn't need to be quoted.

**Comment by JamesKyburz** [comment]
@jeremyfa ok thanks didn't know that. I guess the docker-compose tools I am using aren't using yaml spec 1.2 then :)
