### ISSUE TITLE
breaks when packaging with Browser CommonJS

### ISSUE THREAD

**Issue by coolaj86** [jeremyfa/yaml.js#11]
`YamlRunningUnderNode` is `true` whenever `exports` and `module.expors` are present, but using `pakmanager`, `browserify`, and other CommonJS packaging systems for the browser those are also present.

I'd suggest sniffing `process.versions` or something more node specific.

P.S. The projects I'm working on
- http://jsontoyaml.com
- http://yamltojson.com

**Comment by jeremyfa** [comment]
Good point. I will see what I can do about it.
