### ISSUE TITLE
Array bracket syntax produces parse error

### ISSUE THREAD

**Issue by kyeotic** [jeremyfa/yaml.js#120]
Check out this [runkit](https://runkit.com/embed/0lqpjqh8hb38) example

It doens't like brackets for arrays, even though its valid YAML. [checkout this online parser working](http://yaml-online-parser.appspot.com/?yaml=---%0Apaths%3A%0A++%2Finstance%2F%7Binstance_id%7D%3A%0A++++get%3A%0A++++++tags%3A+%5B%0A++++++++%22Instance%22%0A++++++%5D&type=json)

```yaml
---
paths:
  /instance/{instance_id}:
    get:
      tags: [
        "Instance"
      ]
```

**Comment by michaelgarde** [comment]
Yeah. I get this too.
