### ISSUE TITLE
convert issue of string "ON","OFF"

### ISSUE THREAD

**Issue by hangwang200** [jeremyfa/yaml.js#127]
```
json: 
var obj = {
 'key1':'ON'
}

res = YAML.dump(obj)

yml : 
key: ON
```
but ON is not a string in yaml(it's a boolean value), it's should be 'ON'.

refer:
https://yaml.org/type/bool.html

**Comment by jeremyfa** [comment]
On Yaml 1.2, ON and OFF are strings so this is the expected behaviour.
