### ISSUE TITLE
Disable automatic conversion to non string type

### ISSUE THREAD

**Issue by crystalfp** [jeremyfa/yaml.js#130]
Is it possible to disable the automatic conversion of values? In my yaml file I have: `date: 2019-07-18`. The library converts it to a Date object. Is it possible to disable this conversion and output it as a string? Same for the enty `date: 2014` that is converted to a number.
Thanks for clarifying!
mario

**Comment by jeremyfa** [comment]
AFAIK this is part of the spec. I believe you can add quotes if you want to ensure it is a string
