### ISSUE TITLE
Accept stdin for command line tools

### ISSUE THREAD

**Issue by rektide** [jeremyfa/yaml.js#17]
The command line tools seem to demand input be in the form of a file. By unix convention, if "-" is passed in, the program ought attempt to use stdin, rather than a file. yamljs merely attempts to open a "-" file.

**Comment by arcanis** [comment]
As a workaround, you can probably explicitely use `/dev/stdin` as file name.

**Comment by jeremyfa** [comment]
A fix is planned for this as well.

**Comment by jeremyfa** [comment]
The newly released version `v0.2.0` should work when running: `cat somefile.yml | yaml2json -`
