### ISSUE TITLE
Support yes values for booleans

### ISSUE THREAD

**Issue by tmcw** [jeremyfa/yaml.js#19]
http://mistakes.io/#fce34f14a4d465938bec

Yes and No should parse to `true` and `false` - this is [mentioned in the YAML spec](http://yaml.org/spec/1.1/) (though in vague terms) and supported by most other YAML parsers.

**Comment by jeremyfa** [comment]
This is not a bug. Support for yes and no was dropped starting from 1.2 spec (and yaml.js is a YAML 1.2 parser). The link you are providing is from the 1.1 spec and thus is not relevant anymore. In YAML 1.2, yes should become "yes" instead of true.
