### ISSUE TITLE
unindented comment causes parse error

### ISSUE THREAD

**Issue by dangogh** [jeremyfa/yaml.js#29]
if a comment is included within an indented structure, but is not indented to the same level as the surrounding structure, "Unable to parse" is the result:

If I remove the 2nd comment below, the yaml is parsed correctly.

```

---
Version: 3
parts:
    a: [ 1,2,3]
    b: [4,5,6]
    # this comment is ok
    c: ["a","b"]
# this comment is not ok
    d: [3,4,2]
```

**Comment by calzoneman** [comment]
This is an issue for me as well, is there a fix or am I forced to use an old version of the package?

**Comment by jeremyfa** [comment]
There are several remaining issues like this one. I will spend some time soon to fix them. If this fix is urgent for you, you can either use an old version of the package (if the issue doesn't exist in a previous version) or submit a pull request. Anyway, I will check it out soon. Thanks for the feedback!

**Comment by earth2marsh** [comment]
+1 as this affected me via swagger-tools, which depends on it.

**Comment by aklinkert** [comment]
+1 here. Spend half an hour trying to find out why symfony/yml parses the file but jeremyfa/yaml.js doesn't. Same characteristics for me:

``` yml
list-header:
  - item1
#  - item2  <-- Parse Error
  - item3
  # - item4 <-- thats okay
```

error message:

```
[...]/node_modules/yamljs/lib/Parser.js:268
        throw new ParseException('Unable to parse.', this.getRealCurrentLineNb
              ^
Error: Unable to parse.
```

**Comment by jeremyfa** [comment]
Just fixed it, and added unit tests so that it won't break again. Thanks for the feedback! (I will release the fix on NPM soon)

**Comment by dangogh** [comment]
very cool..   thanks!

**Comment by aklinkert** [comment]
Cool, thanks for the quick support! :+1:
