### ISSUE TITLE
XMLHttpRequests deprecated

### ISSUE THREAD

**Issue by faroit** [jeremyfa/yaml.js#34]
loading yaml.js results in a deprecation warnings in most recent browser version.

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

To fix this, xhr open() should be called using the async=true option

**Comment by jeremyfa** [comment]
Hi faroit,

If you are providing a callback to YAML.load(), the call should be asynchronous:

``` js
YAML.load('file.yml', function(result)
{
    nativeObject = result;
});
```

It is not a good idea to load a YAML file synchronously on the browser anyway (And that is probably the reason why synchronous XHR is deprecated).

**Comment by faroit** [comment]
ah okay. Thanks for explaining this to me! :+1:

**Comment by jeremyfa** [comment]
You're welcome!
