### ISSUE TITLE
yamljs doesn't seem to like map keys and list items with line breaks

### ISSUE THREAD

**Issue by gisode** [jeremyfa/yaml.js#35]
According to yamllint.com (and to the spec as far as I understand it) this is valid YAML:

```
foo
bar: |
  baz
```

And this also:

```
- foo
  bar
```

yamljs stumbles on both with parse errors. Also on combinations of both (which is how I noticed):

```
- really very long text for a map key where one could reasonably expect 
  a line-break:
    - some more stuff
    - and yet more stuff which is also very long-winded and requires a
      line-break
```

Tested with yamljs 0.2.2

**Comment by jeremyfa** [comment]
Hi, thanks for the feedback. Unfortunately there are no plans on implementing this specific case, unless Symfony's Yaml parser (where yaml.js was ported from) also handles it.
