### ISSUE TITLE
Parsing double quoted line breaks is not supported

### ISSUE THREAD

**Issue by ghost** [jeremyfa/yaml.js#36]
Certain YAML libraries like [SnakeYAML](http://snakeyaml.org) can generate documents that feature [double quoted line breaks (see example 7.5)](http://www.yaml.org/spec/1.2/spec.html#id2786942) in order to wrap long double-quoted scalars. Here's an example of such a document:

```
--- "I've made this string so long that SnakeYAML will wrap it! Mwarhar. My long strings\
  \ shall dominate the world!"
```

Ruby 2.2.1's YAML parser (which wraps libyaml) and JS-YAML can convert these documents back to this string as expected:

```
"I've made this string so long that SnakeYAML will wrap it! Mwarhar. My long strings shall dominate the world!"
```

However, yaml.js claims that this is invalid syntax, throwing a `ParseException` with the following details:

```
message: "Unable to parse.", 
parsedLine: 1, 
snippet: "  \ shall dominate the world!""
```

This bug may impact interoperability with all systems that generate double-quoted scalars.

**Comment by jeremyfa** [comment]
Hi, thanks for the feedback. Unfortunately there are no plans on implementing this specific case, unless Symfony's Yaml parser (where yaml.js was ported from) also handles it.
