### ISSUE TITLE
[Request] Vert.X Support

### ISSUE THREAD

**Issue by darylteo** [jeremyfa/yaml.js#4]
Hi there Jeremy,

  I tried to use your yaml parser in vert.x. However it is not supported out of the box as your library is completely wrapped in a closure and depends on the existence of browser.window or node.js module exports... Unfornuately Vertx does not have either of those... so I had to hack into it a couple of extra lines.

https://gist.github.com/3652677

Kind Regards,
Daryl Teo

**Comment by jeremyfa** [comment]
This should fixed by now.
