### ISSUE TITLE
Empty arrays cause errors

### ISSUE THREAD

**Issue by tayloa45** [jeremyfa/yaml.js#46]
The following...

```
y = require('yamljs');
console.log(y.parse(y.stringify({a:[]})));
```

...results in `{ a: null }`.

Obviously this is not right and it is causing errors in our app.

**Comment by jeremyfa** [comment]
Can you confirm you are using yamljs v0.2.3?

**Comment by tayloa45** [comment]
Yes, I am.

**Comment by jeremyfa** [comment]
I reproduce the issue indeed. Thanks for reporting, I will look into it.

**Comment by tayloa45** [comment]
No problem. Thanks!

**Comment by jeremyfa** [comment]
Should be ok now.

**Comment by tayloa45** [comment]
Fantastic work — I'll take my nasty hack workaround out now.

Thanks a lot.
