### ISSUE TITLE
Minified version triggers parsing error in Safari

### ISSUE THREAD

**Issue by enykeev** [jeremyfa/yaml.js#50]
`SyntaxError: Cannot declare a parameter named 'e' as it shadows the name of a strict mode function.`

This is the fragment that triggers the error `(function e(e,t,n){`. 

For some reason not described in ECMA-262, Safari decides that function name and function argument should not be the same in strict mode.

**Comment by jeremyfa** [comment]
Interesting. Wondering if newer versions of `uglifyjs` handle this.

**Comment by enykeev** [comment]
Cleaning my issues tab. Closing for lack of progress.
