### ISSUE TITLE
How to force explicit string quoting

### ISSUE THREAD

**Issue by JayChandler** [jeremyfa/yaml.js#51]
Hello

I have following JSON

<pre>
 "services" : {
          "memcached" : {
            "class" : "Memcached",
            "calls" : [
              [ "addServers", ["%memcache_hosts%"] ]
            ]
         },
         "doctrine.cache.memcached" : {
           "class" : "Doctrine\\Common\\Cache\\MemcachedCache",
           "calls" : [
              [ "setMemcached", ["@memcached"] ]
            ]
         },
         "sync_cache": {
           "class" : "Doctrine\\Common\\Cache\\MemcachedCache",
           "calls" : [
               [ "setMemcached", [ "@memcached" ] ],
               [ "setNamespace", [ 'a' ] ]
           ]
        }
      }  
</pre>

And it give me that yaml output

<pre>
services:
    memcached:
        class: Memcached
        calls:
            - [addServers, ['%memcache_hosts%']]
    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [setMemcached, ['@memcached']]
    sync_cache:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [setMemcached, ['@memcached']]
            - [setNamespace, [a]]
</pre>

I need the - [setNamespace, [**a**]] to look like this - [setNamespace, [**"a"**]]. How can i do this ?

**Comment by jeremyfa** [comment]
There is currently no way to change this behaviour. The above dumped yaml is perfectly valid and that is all yaml.js cares about.

It would be possible to add an option to force the use of quotes, but this is definitely not in my plans. However feel free to submit a pull request with the change if you want to do it yourself.

**Comment by stefaneg** [comment]
There is the issue of "yes" and yes, "off" and off, which are not the same in yaml. One is a string, the other a boolean. Just sayin...
