### ISSUE TITLE
Update glob version

### ISSUE THREAD

**Issue by hassankhan** [jeremyfa/yaml.js#64]
The version of `glob` used by this library uses a vulnerable version of `minimatch` as per this advisory: https://nodesecurity.io/advisories/118

I can't install a package that relies on this because of it, would be great if you could help. Thanks :)

**Comment by jeremyfa** [comment]
Indeed, but even latest version of glob has the issue. The dependency needs to be updated there.
Related issue: https://github.com/isaacs/node-glob/issues/268

Also note that glob is only used for the command-line utility, not the yaml parsing itself, but as soon as they fix the minimatch dependency, I will update glob!

**Comment by plynchnlm** [comment]
isaacs/node-glob#268 is now closed, and the fix is in 7.0.5 of node-glob.

**Comment by jeremyfa** [comment]
Well, in fact glob dependency already up to date on the yaml.js repo (and on npm). There is still (indirect) dependencies to older versions of minimatch, but they are only dev dependencies, so they should not affect production use.

**Comment by plynchnlm** [comment]
The latest tagged version of yaml.js is v0.2.7, which still has the old version of glob.  Are you planning to tag 0.2.8 soon?

**Comment by jeremyfa** [comment]
It seems that the tag was not pushed, but the repo on npm was already up to date. It should be ok now!
