### ISSUE TITLE
stringify not respecting inline 

### ISSUE THREAD

**Issue by muka** [jeremyfa/yaml.js#65]
Hi,

In my code I try to have an indent output to be appended to another yaml structure (from template)

I read in api docs 

```
    # @param [Object]   input                   The JavaScript value
    # @param [Integer]  inline                  The level where you switch to inline YAML
    # @param [Integer]  indent                  The level of indentation (used internally)
    ...
```

So I would expext that `yamljs.stringify({ Test: { hello: "world" } }, 2, 2)` would put `Test` with an indentation of 2. It is instead always put at the beginning of the line

Is it my misunderstanding or is it a bug ?

Thank you

**Comment by jeremyfa** [comment]
Can you paste here the output you expect, and the one you get?

**Comment by muka** [comment]
Thanks for the fast response!

Actually I found the property works as expected, If I put inline=4 i get 

```
StatusType:
    type: enum
    displayName: StatusType
```

I'd expected from the indent property to set the base indentation level to start from, eg

```
  StatusType:
    type: enum
    displayName: StatusType
```

This seems to happen here around https://github.com/jeremyfa/yaml.js/blob/develop/src/Yaml.coffee#L82

I see `indentation` is set and `Dumper.dump` indent set to 0

Maybe indent doesn't mean what I think?

**Comment by muka** [comment]
A meanwhile solution :dart: 

```
yamljs.stringify(obj).split("\n").map(function(line) {
        return "  " + line;
      }).join("\n")
```

**Comment by jeremyfa** [comment]
Options should be `indent`. If you find a case where the indent option doesn't work as expected, feel free to file an issue with the exact use case. Closing this one for now.
