### ISSUE TITLE
require.extensions warning in Webpack

### ISSUE THREAD

**Issue by chito256** [jeremyfa/yaml.js#69]
Hi guys, I have just installed and used `yamljs` for my project. I also use Webpack for my project. When compiling, everything works just fine but there were a few warnings.

```
WARNING in ./~/yamljs/lib/Yaml.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/yamljs/lib/Yaml.js
Critical dependencies:
78:43-50 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/yamljs/lib/Yaml.js 78:43-50
```

Why did this happen? Is there a way to ignore or fix this?

Here is my Webpack configuration:

```
const webpack = require('webpack');
const path = require('path');

const nodeENV = process.env.NODE_ENV; // can either be 'development' or 'production'
const isProd = nodeENV === 'production';

let config = {
    entry: [
        './app/index.js'
    ],
    output: {
        path: path.join(__dirname, 'app', 'build'),
        filename: 'bundle.js'
    },
    node: {
    __filename: true,
    __dirname: true,
    "child_process": "empty"
  },
  target: 'node',
  module: {
    loaders: [
        { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader' },
        { test: /\.json$/, loader: 'json-loader' }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
        'process.env': { 'NODE_ENV' : JSON.stringify(nodeENV) }
    })
  ]
};

module.exports = config;
```

Thanks in advance! :smiley:

**Comment by jeremyfa** [comment]
Hi, thanks for reporting!

The warning makes sense. yamljs provides a register() function to allow to require directly yaml file. Not sure how to mute the warning with Webpack, but as long as you don't call register(), you should be just fine.

**Comment by chito256** [comment]
@jeremyfa Ohh, no wonder it gave me errors when I tried to use the `load()` function. Thanks for your reply. Glad I could help, hope it will be fixed :smiley:

**Comment by aeweidne** [comment]
@chito256 ever figure out how to silence the warnings?
