### ISSUE TITLE
Auto-detect YAML headers in non full-YAML files

### ISSUE THREAD

**Issue by CharlesNepote** [jeremyfa/yaml.js#75]
Some data or content formats use YAML as a header. Some examples:

- [http://csvy.org/](http://csvy.org/)
- in [PANDOC](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block)
- in [Jekyll](https://jekyllrb.com/docs/frontmatter/)
- in [Grave flat file CMS](https://learn.getgrav.org/basics/basic-tutorial)
- in [R markdown](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
- and so on... we can find many more examples.

It would be very good to let yamljs auto-detect YAML blocks.

Thanks!

**Comment by jeremyfa** [comment]
You point out the exact reason why this won't be done: _"and so on..."_

It is not (and should not be) the role of yaml.js to extract content from other file formats. Instead, it is the job of your Jekyll/R markdown/PANDOC/... parser to extract the yaml portion itself, and maybe use yaml.js (or any other yaml parser) to parse the yaml part and do something with it.

**Comment by CharlesNepote** [comment]
I understand your point of view, even if it's not what I was hoping ;-)

These file formats are including both YAML header and other stuf to fight against multiplication of files. Of course I can extract its YAML header from a data.csvy file and give it to yaml.js, but there is a bit much effort. Some YAML parsers already accept YAML frontmatter, like https://github.com/debrouwere/yaml2json or https://github.com/bronze1man/yaml2json.

I was very interested by yours as it can run in a browser.

Thanks!
