### ISSUE TITLE
require.extensions deprecated

### ISSUE THREAD

**Issue by momewrath** [jeremyfa/yaml.js#83]
I ran into the issue that was brought up in issue #69.  I am not using the register function but I still see the warnings.  I looked into it a bit further and discovered that require.extensions has actually been deprecated in Node.js.  It unfortunately isn't just a matter of webpack not supporting it.

https://nodejs.org/api/globals.html#globals_require_extensions

Any plans to handle this differently so as not to use a deprecated function?

**Comment by aeweidne** [comment]
plz halp

**Comment by jeremyfa** [comment]
The incriminated code has been removed from latest updated version (v0.3.0). Thanks for reporting!

**Comment by aeweidne** [comment]
Thanks for the response!  Super appreciated.
