### ISSUE TITLE
json2yaml in node.js?

### ISSUE THREAD

**Issue by luisfcofv** [jeremyfa/yaml.js#93]
Is it possible to json2yaml in node.js without installing the cli tools?

**Comment by jeremyfa** [comment]
I am not sure I understand the question. If you want to convert JSON to YAML, you can just use the regular yamljs node module, load you JSON and use yamljs to dump it to YAML.

**Comment by luisfcofv** [comment]
Got it, that's actually what I want, JSON to YAML. I thought it was not possible with the node module.
